### ISSUE TITLE
Can an Instagram Like navigation be done with this Library

### ISSUE THREAD

**Issue by mathemandy** [aartikov/Alligator#21]
I tested the advanceSwitcher sample and noticed that when the stacks for a tab are emptied, it closes the app, while other stacks are still on other stab. 

Question 1.  Can i make just one entry point to the app - (this way all stacks can end inn this tab)
Question 2.  Can all stacks be emptied before closing the App

**Comment by aartikov** [comment]
You can store a history of visited tabs in your activity and call an appropriate method (`goBack` or `switchTo`) on back pressed. These methods can be helpful to do it:
`screenSwitcher.getScreen()`
`screenSwitcher.getCurrentFragment()`
`new FragmentStack(fragmentManager, containerId).getFragmentCount()`

Alligator does not support this behavior out of box because it is not recommended by Material design guidelines. There was a line on [material.io](https://material.io/design/components/bottom-navigation.html): _"On Android, the Back button does not navigate between bottom navigation bar views"._ But I don't manage to find it now. May be the rules have been changed.

**Comment by mathemandy** [comment]
Thanks for this Guide. Great library Tool you have. I will get back to you
